language: 
  - ruby
  - java
jdk: openjdk8
rvm:
  - 2.6.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
install: 
  - gem install jekyll
  - gem install s3_website
  # - gem install html-proofer
script:
  - bundle install
  - JEKYLL_ENV=production bundle exec jekyll build  
  # - htmlproof _site
cache: bundler  
after_success: s3_website push
sudo: false
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
