language: ruby
rvm:
  - 2.2
install: gem install jekyll && gem install s3_website
script:
  - JEKYLL_ENV=production bundle exec jekyll build
end
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
after_success: travis_retry bundle exec s3_website push --headless

