language: ruby
rvm:
  - 2.2.0
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 
install: 
  - gem install listen 3.0.5
  - gem install jekyll
  - gem install s3_website
  # - gem install html-proofer
script:
  - bundle install
  - JEKYLL_ENV=production bundle exec jekyll build  
  # - htmlproof _site
after_success: s3_website push
sudo: false
