language: ruby
rvm:
  - 2.2.0
install: gem install jekyll && gem install s3_website
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
after_success: travis_retry bundle exec s3_website push --headless
sudo: false
