language: ruby
rvm:
  - 2.2
install: gem install jekyll && gem install s3_website && gem install public_suffix
script:
  - JEKYLL_ENV=production bundle exec jekyll build
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false
after_success: travis_retry bundle exec s3_website push --headless

