language: ruby
rvm:
  - 2.1
install: gem install jekyll && gem install s3_website
script:
  - bundle exec jekyll build  
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
after_success: travis_retry bundle exec s3_website push --headless
sudo: false
