# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sugardrum
email: sugardrum@gmail.com
description: Sugardrum create folk/indie storytelling songs with beautiful vocals, fingerpicking acoustic guitar, cello, electronica and percussion. 
mediaurl: http://files.sugardrum.com/
paginate: 15
paginate_path: "/blog/page:num"
permalink: "blog/:year/:month/:day/:title/"

# Build settings
markdown: kramdown
exclude: [node_modules,Gruntfile.js,package.json,Gemfile,wedding,s3-error-redirects.xml,blog-images,s3_website]
baseurl: ""
url: http://www.sugardrum.com


# Site settings

# baseurl: "" # the subpath of your site, e.g. /blog


# twitter_username: sugardrummusic
# github_username:  jekyll

gems :
  - jekyll-paginate

# url: "http://www.sugardrum.com" # the base hostname & protocol for your site
# paginate: 5
# pagination_path: "/blog/page:num/"
# permalink: "blog/:title/"

# # Build settings
# markdown: kramdown


